# Generated by Django 5.0.3 on 2025-02-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('service', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(max_length=100)),
                ('doctor_image', models.FileField(blank=True, null=True, upload_to='doctor_images/')),
                ('qualification', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('reg_no', models.BigIntegerField(blank=True, null=True)),
                ('doctor_location', models.TextField(blank=True, null=True)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
            ],
        ),
    ]
