# Generated by Django 5.0.3 on 2025-02-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_doctor',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
