# Generated by Django 5.0.3 on 2025-02-18 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_doctor', '0002_alter_booking_doctor_phone_number'),
        ('doctor_details', '0002_doctor_details_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_doctor',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking_doctor',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_details.doctor_details'),
        ),
    ]
