# Generated by Django 5.0.3 on 2025-02-26 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_doctor', '0003_booking_doctor_created_at_booking_doctor_doctor'),
        ('user_profile', '0004_rename_user_name_user_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_doctor',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking_doctor',
            name='doc_phone_number',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking_doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking_doctor',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking_doctor',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking_doctor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking_doctor',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking_doctor',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.user_profile'),
        ),
        migrations.AddField(
            model_name='booking_doctor',
            name='user_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
