# Generated by Django 5.0.3 on 2025-03-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_doctor', '0009_alter_favorite_doctor_doctor_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite_doctor',
            name='doctor_phone_no',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
