# Generated by Django 5.0.3 on 2025-03-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_doctor', '0010_alter_favorite_doctor_doctor_phone_no'),
        ('doctor_details', '0004_doctor_details_doctor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite_doctor',
            name='doctor_phone_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='favorite_doctor',
            unique_together={('phone_number', 'doctor')},
        ),
    ]
