# Generated by Django 5.0.3 on 2025-03-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_doctor', '0012_alter_favorite_doctor_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite_doctor',
            name='doctor_email',
        ),
    ]
