# Generated by Django 5.0.3 on 2025-03-08 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_doctor', '0013_remove_favorite_doctor_doctor_email'),
        ('user_profile', '0004_rename_user_name_user_profile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_doc_only_user_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_phone_number', models.BigIntegerField()),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('user_photo', models.FileField(blank=True, null=True, upload_to='')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.user_profile')),
            ],
            options={
                'unique_together': {('phone_number', 'doctor_phone_number')},
            },
        ),
    ]
