# Generated by Django 5.0.3 on 2025-03-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_doctor', '0014_chat_doc_only_user_chat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking_doctor',
            unique_together={('phone_number', 'doc_phone_number', 'booking_date', 'booking_time')},
        ),
    ]
