# Generated by Django 5.0.3 on 2025-04-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_doctor', '0015_alter_booking_doctor_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_doctor',
            name='doc_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking_doctor',
            name='doc_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking_doctor',
            name='doc_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
