# Generated by Django 5.0.3 on 2025-04-06 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_doctor', '0016_booking_doctor_doc_age_booking_doctor_doc_email_and_more'),
        ('doctor_details', '0008_doctor_details_doc_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='show_booked_doc_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_phone_number', models.BigIntegerField()),
                ('doctor_phone_no', models.BigIntegerField(blank=True, null=True)),
                ('doctor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_image', models.FileField(blank=True, null=True, upload_to='')),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('reg_no', models.BigIntegerField(blank=True, null=True)),
                ('doctor_location', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_details.doctor_details')),
            ],
            options={
                'unique_together': {('patient_phone_number', 'doctor_phone_no')},
            },
        ),
    ]
