// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoOWEcvipbvBTTfb0mbt6k5NjNHg67vpo',
    appId: '1:680664981067:web:769578378e64f3a50d37ce',
    messagingSenderId: '680664981067',
    projectId: 'healthhub-78dde',
    authDomain: 'healthhub-78dde.firebaseapp.com',
    storageBucket: 'healthhub-78dde.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhUinOmS7OAKU0vwtnQJuq5AyTjy_ZqhY',
    appId: '1:680664981067:android:c2e93ecbf1d82ae20d37ce',
    messagingSenderId: '680664981067',
    projectId: 'healthhub-78dde',
    storageBucket: 'healthhub-78dde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBilxihA7iLQgFno6LWPZnw4RMUs5T4qJQ',
    appId: '1:680664981067:ios:e87d4f49a29a94af0d37ce',
    messagingSenderId: '680664981067',
    projectId: 'healthhub-78dde',
    storageBucket: 'healthhub-78dde.firebasestorage.app',
    androidClientId: '680664981067-4jjgbmaqq1s95ojp3ui174880hi6s754.apps.googleusercontent.com',
    iosClientId: '680664981067-bd3ka8g72p6mmrl2gb35emgdlpj4hioh.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBilxihA7iLQgFno6LWPZnw4RMUs5T4qJQ',
    appId: '1:680664981067:ios:e87d4f49a29a94af0d37ce',
    messagingSenderId: '680664981067',
    projectId: 'healthhub-78dde',
    storageBucket: 'healthhub-78dde.firebasestorage.app',
    androidClientId: '680664981067-4jjgbmaqq1s95ojp3ui174880hi6s754.apps.googleusercontent.com',
    iosClientId: '680664981067-bd3ka8g72p6mmrl2gb35emgdlpj4hioh.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoOWEcvipbvBTTfb0mbt6k5NjNHg67vpo',
    appId: '1:680664981067:web:ae5d46f20bf663f10d37ce',
    messagingSenderId: '680664981067',
    projectId: 'healthhub-78dde',
    authDomain: 'healthhub-78dde.firebaseapp.com',
    storageBucket: 'healthhub-78dde.firebasestorage.app',
  );
}
