# Generated by Django 5.0.3 on 2025-03-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_number', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('cure_disases', models.CharField(blank=True, max_length=100, null=True)),
                ('product_image', models.TextField(blank=True, null=True)),
                ('about_product', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
