# Generated by Django 5.0.3 on 2025-03-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_pur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_details',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
