# Generated by Django 5.0.3 on 2025-03-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_pur', '0002_medicine_details_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_details',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
