# Generated by Django 5.0.3 on 2025-03-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_pur', '0003_alter_medicine_details_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='pati_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Pry_phone_number', models.BigIntegerField()),
                ('sec_phone_number', models.BigIntegerField(blank=True, null=True)),
                ('flat_house_name', models.CharField(blank=True, max_length=100, null=True)),
                ('area_building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.BigIntegerField(blank=True, null=True)),
                ('Town_City', models.CharField(blank=True, max_length=100, null=True)),
                ('state_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='medicine_details',
            name='product_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
