# Generated by Django 5.0.3 on 2025-03-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_pur', '0004_pati_address_alter_medicine_details_product_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pati_address',
            name='address_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
