# Generated by Django 5.0.3 on 2025-03-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_pur', '0005_pati_address_address_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pati_address',
            name='address_id',
        ),
    ]
