# Generated by Django 5.0.3 on 2025-03-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_pur', '0006_remove_pati_address_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pati_address',
            name='sequence_number',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='pati_address',
            unique_together={('Pry_phone_number', 'sequence_number')},
        ),
    ]
