# Generated by Django 5.0.3 on 2025-03-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_pur', '0007_pati_address_sequence_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pati_address',
            old_name='Pry_phone_number',
            new_name='pry_phone_number',
        ),
        migrations.RenameField(
            model_name='pati_address',
            old_name='Town_City',
            new_name='town_city',
        ),
        migrations.AlterUniqueTogether(
            name='pati_address',
            unique_together={('pry_phone_number', 'sequence_number')},
        ),
    ]
