# Generated by Django 5.0.3 on 2025-03-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_pur', '0009_alter_pati_address_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_placed_details',
            name='sequence_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
