# Generated by Django 5.0.3 on 2025-03-23 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_pur', '0011_alter_order_placed_details_product_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_to_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pry_phone_number', models.BigIntegerField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_number', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('cure_disases', models.CharField(blank=True, max_length=100, null=True)),
                ('product_image', models.FileField(blank=True, null=True, upload_to='')),
                ('about_product', models.TextField(blank=True, null=True)),
                ('product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_pur.medicine_details')),
            ],
        ),
    ]
