# Generated by Django 5.0.3 on 2025-03-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_pur', '0012_add_to_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_placed_details',
            name='purchase_pay_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_placed_details',
            name='purchase_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_placed_details',
            name='purchase_total_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
