# Generated by Django 5.0.3 on 2025-03-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_pur', '0013_order_placed_details_purchase_pay_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_placed_details',
            name='purchase_total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
