# Generated by Django 5.0.3 on 2025-03-03 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone_no', models.BigIntegerField()),
                ('doc_phone_no', models.BigIntegerField()),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('doctor', 'Doctor')], max_length=10)),
                ('message', models.TextField()),
                ('datestamp', models.DateField(default=django.utils.timezone.now)),
                ('timestamp', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
