# Generated by Django 5.0.3 on 2025-03-03 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='datestamp',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.TimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
