# Generated by Django 5.0.3 on 2025-03-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chatmessage_datestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_off', models.BooleanField(blank=True, null=True)),
                ('last_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
