# Generated by Django 5.0.3 on 2025-04-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_sstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='medicine_images/'),
        ),
    ]
