# Generated by Django 5.0.3 on 2025-04-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chatmessage_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='product_image',
            new_name='image',
        ),
    ]
