# Generated by Django 5.0.3 on 2025-02-09 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_user_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
