# Generated by Django 5.0.3 on 2025-02-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_user_profile_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='user_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
