# Generated by Django 5.0.3 on 2025-03-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_rename_user_name_user_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='doc_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
