# Generated by Django 5.0.3 on 2025-03-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_user_profile_doc_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='doc_status',
            new_name='user_status',
        ),
    ]
