# Generated by Django 5.0.3 on 2025-02-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='like',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
