# Generated by Django 5.0.3 on 2025-02-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_details', '0002_doctor_details_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='doctor_phone_no',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
