# Generated by Django 5.0.3 on 2025-03-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_details', '0005_remove_doctor_details_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='like',
            field=models.BooleanField(null=True),
        ),
    ]
