# Generated by Django 5.0.3 on 2025-03-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_details', '0006_doctor_details_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor_details',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
