# Generated by Django 5.0.3 on 2025-03-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_details', '0007_doctor_details_age_doctor_details_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='doc_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
